server:
  port: 8071
spring:
  application:
    name: "configserver"
  profile:
    active: prod
  cloud:
    config:
      import: “optional:configserver:http://localhost:8071”
      server:
        git:
          uri: "https://github.com/pp148656/ukg-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true

