CREATE TABLE IF NOT EXISTS `course`(
`id` INT AUTO_INCREMENT PRIMARY KEY,
`title` VARCHAR(30) NOT NULL,
`duration` VARCHAR(20) NOT NULL,
`author` VARCHAR(30) NOT NULL,
`created_at` DATE DEFAULT NULL,
`created_by` VARCHAR(20) DEFAULT NULL,
`updated_at` DATE DEFAULT NULL,
`updated_by` VARCHAR(20) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `enrollment`(
`id` INT AUTO_INCREMENT PRIMARY KEY,
`course_id` INT DEFAULT NULL,
`emp_id` INT DEFAULT NULL,
`status` BOOLEAN DEFAULT FALSE

);