services:
  first:
    image: **
    container_name: first
    ports:
      - 8090:8090
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ems

  course-service:
    image: **
    container_name: course-service
    ports:
      - 8080:8080
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      - H2_OPTIONS=-webAllowOthers
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ems
